#!/bin/sh
set -e

in=""
out=""
eboot=""
paid="0x3800000000000011"
while [ $# -gt 0 ]; do
	case "$1" in
		-in=*) in="${1#*=}"; shift ;;
		-out=*) out="${1#*=}"; shift ;;
		-eboot=*) eboot="${1#*=}"; shift ;;
		--paid) paid="$2"; shift 2 ;;
		--paid=*) paid="${1#*=}"; shift ;;
		*) shift ;;
	esac
done

if [ -n "$eboot" ]; then
	eboot_dir=$(dirname "$eboot")
	eboot_base=$(basename "$eboot")
	mkdir -p "$eboot_dir"
	/lib/OpenOrbisSDK/bin/linux/create-eboot -in "$in" -out "$eboot" -paid "$paid"
	if [ "$eboot_base" != "eboot.bin" ]; then
		mv "$eboot" "$eboot_dir/eboot.bin"
		mv "$eboot_dir/eboot.bin" "$eboot"
	fi
fi

if [ -n "$out" ]; then
	cp "$in" "$out"
fi
